version: "3.5"

services:
  calibre-server:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./recipes:/opt/recipes
      - ./users.sqlite:/opt/users.sqlite
      - ./library:/opt/library