version: "3.5"

services:
  calibre-server:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./recipes:/opt/recipes:rw
      - ./users.sqlite:/opt/users.sqlite:rw
      - ./library:/opt/library:rw
    user: root  # Start as root to ensure permissions work
